---
Serilog:
  MinimumLevel:
    Default: Verbose
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
  WriteTo:
  - Name: MSSqlServer
    Args:
      connectionString: data source=localhost;initial catalog=BuBu;persist security
        info=True; Integrated Security=SSPI;
      tableName: Log
AuthSettings:
  Secret: bububeeVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!
  RefreshTokenExpiresDays: 365
SqlDbSettings:
  ConnectionString: Server=localhost;Database=myHAVEN_Auth;Trusted_Connection=True;
RedisSettings:
  ConnectionString: klip
AzureServiceBusSettings:
  ConnectionString: klip-klip
  SubscriptionClientName: myHAVEN-dev
management:
  endpoints:
    actuator:
      exposure:
        include: [ "*" ]
  tracing:
    alwaysSample: true
    useShortTraceIds: true
    exporter:
      zipkin:
        useShortTraceIds: true
        endpoint: http://zipkinserver:9411/api/v2/spans
