---
Serilog:
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
  WriteTo:
  - Name: MSSqlServer
    Args:
      connectionString: data source=Xion-Mac3;initial catalog=BuBu;persist security
        info=True; Integrated Security=SSPI;
      tableName: Log
SqlDbSettings:
  ConnectionString: Server=Xion-Mac3;Database=myHAVEN_Auth;Trusted_Connection=True;
RedisSettings:
  ConnectionString: klip
AzureServiceBusSettings:
  ConnectionString: klip-klip
  SubscriptionClientName: myHAVEN-dev
