---
SqlDbSettings:
  ConnectionString: Server=localhost;Database=myHAVEN_Auth;Trusted_Connection=True;
RedisSettings:
  ConnectionString: klip
management:
  endpoints:
    actuator:
      exposure:
        include: [ "*" ]
  tracing:
    alwaysSample: true
    useShortTraceIds: true
    exporter:
      zipkin:
        useShortTraceIds: true
        endpoint: http://zipkinserver:9411/api/v2/spans
